/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.fmchan;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Order;

class CanvasTest {
	private static Canvas canvas;
	
	@BeforeAll
	public static void setUp() throws Exception {
		canvas = new Canvas(20, 5);
	}

	@Test
    @Order(1)
	public void create() throws Exception {
        String expected = """
        ----------------------
        |                    |
        |                    |
        |                    |
        |                    |
        |                    |
        ----------------------
        """;
		assertEquals(canvas.render().trim(), expected.trim());
	}

    @Test
    @Order(2)
	public void line() throws Exception {
        canvas.drawLine(1, 1, 4, 1);
        String expected = """
        ----------------------
        |                    |
        | XXXX               |
        |                    |
        |                    |
        |                    |
        ----------------------
        """;
		assertEquals(canvas.render().trim(), expected.trim());
    }
    @Test
    @Order(3)
	public void rectangle() throws Exception {
        canvas.drawLine(1, 1, 4, 1);
        canvas.drawRectangle(2, 2, 10, 4);
        String expected = """
        ----------------------
        |                    |
        | XXXX               |
        |  XXXXXXXXX         |
        |  X       X         |
        |  XXXXXXXXX         |
        ----------------------
        """;
		assertEquals(canvas.render().trim(), expected.trim());
    }
    @Test
    @Order(4)
	public void bucketFill() throws Exception {
        canvas.drawLine(1, 1, 4, 1);
        canvas.drawRectangle(2, 2, 10, 4);
        canvas.doBucketFill(3, 3, 'o');
        String expected = """
        ----------------------
        |                    |
        | XXXX               |
        |  XXXXXXXXX         |
        |  XoooooooX         |
        |  XXXXXXXXX         |
        ----------------------
        """;
		assertEquals(canvas.render().trim(), expected.trim());
    }
}
