/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.fmchan;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class CommandTest {
    private static Controller controller = new Controller();

    @Test
	public void create() throws Exception {
        String expected = """
        ----------------------
        |                    |
        |                    |
        |                    |
        |                    |
        |                    |
        ----------------------
        """;
		assertEquals(controller.assign("C 20 5").trim(), expected.trim());
	}

    @Test
	public void line() throws Exception {
        String expected = """
        ----------------------
        |                    |
        | XXXX               |
        |                    |
        |                    |
        |                    |
        ----------------------
        """;
        controller.assign("C 20 5");
		assertEquals(controller.assign("L 2 2 5 2").trim(), expected.trim());
    }
    @Test
	public void rectangle() throws Exception {
        String expected = """
        ----------------------
        |                    |
        | XXXX               |
        |  XXXXXXXXX         |
        |  X       X         |
        |  XXXXXXXXX         |
        ----------------------
        """;
        controller.assign("C 20 5");
        controller.assign("L 2 2 5 2");
		assertEquals(controller.assign("R 3 3 11 5").trim(), expected.trim());
    }
    @Test
	public void bucketFill() throws Exception {
        String expected = """
        ----------------------
        |                    |
        | XXXX               |
        |  XXXXXXXXX         |
        |  XoooooooX         |
        |  XXXXXXXXX         |
        ----------------------
        """;
        controller.assign("C 20 5");
        controller.assign("L 2 2 5 2");
        controller.assign("R 3 3 11 5");
		assertEquals(controller.assign("B 4 4 o").trim(), expected.trim());
    }
}
